### PR TITLE
media-tv/kodi: add multi-plateform support

### PR DESCRIPTION
**Pull request by dguglielmi**
Discussion in #7

### CODE REVIEW

**Comment by dguglielmi** [comment]
This is building well on my system with IUSE="X gbm wayland"

Kodi automatically switch from X11 to wayland if we use an X11 or Wayland session. I can start a GBM session with a custom systemd unit files.

@parona-source : Can you have a look at this too ?

**Comment by parona-source** [comment]
Yes, im currently looking at this and already tried on my system with MYCMAKEARGS="-DCORE_PLATFORM_NAME=\"gbm x11 wayland\"".

Atm looks good, but still checking whats the deal with binary names that apparently got me confused.

**Comment by parona-source** [comment]
LGTM

**Comment by parona-source** [comment]
I rescind that. The patch I made needs to be amended

**Comment by dguglielmi** [comment]
Do you want a new revbump or sould I merge it to media-tv/kodi-21.0-r3 ?

**Comment by parona-source** [comment]
Just merge it into -r3.

Also this should fix the patch.

```diff
diff --git a/media-tv/kodi/files/kodi-21-optional-ffmpeg-libx11.patch b/media-tv/kodi/files/kodi-21-optional-ffmpeg-libx11.patch
index 27c1b69..1d0805a 100644
--- a/media-tv/kodi/files/kodi-21-optional-ffmpeg-libx11.patch
+++ b/media-tv/kodi/files/kodi-21-optional-ffmpeg-libx11.patch
@@ -4,7 +4,7 @@
    else()
      list(APPEND ffmpeg_conf --disable-vdpau)
    endif()
-+  if (CORE_PLATFORM_NAME STREQUAL x11)
++  if ("x11" IN_LIST CORE_PLATFORM_NAME_LC)
 +    list(APPEND ffmpeg_conf --enable-xlib)
 +  else()
 +    list(APPEND ffmpeg_conf --disable-xlib)
 ```

**Comment by parona-source** [comment]
LGTM

second times the charm

**Comment by dguglielmi** [comment]
> LGTM
> 
> second times the charm

I let you push it :)

**Pull request merged**
