### PR TITLE
kodi-addon.eclass: infer CODENAME from PV

### PR DESCRIPTION
**Pull request by parona-source**

### CODE REVIEW

**Comment by parona-source** [comment]
Also with the kodi dependency I relaxed it with https://github.com/kodi-overlay/kodi-overlay/commit/1b5365b09201e51cb33fea0c30e29c8473fd3601

So bumping the CODENAME to match the users kodi versions shouldn't be necessary.

Really the only place where kodi plugins might stop working with new kodi is with anything that touches gui.

image

kodi-21 for reference has xbmc.python 3.0.1 (ABI 3.0.0), xbmc.gui 5.17.0 (ABI 5.17.0), xbmc.json 13.5.0 (ABI 6.0.0), xbmc.metadata 2.1.0 (ABI 1.0) and xbmc.addon 21.0.0 (ABI 12.0)

**Review by dguglielmi — APPROVED** [review]
LGTM.

Tested for live and non-live ebuilds.

Feel free to merge it!

**Comment by parona-source** [comment]
I'll do a mass change of removing CODENAME="" where it isnt needed, also noticed 21.9999 vs 9999 at least in some packages both used the default branch. So this eclass change should fix it automagically.

**Review by dguglielmi — APPROVED** [review]
LGTM

**Pull request merged**
